import { Shell } from '../../components/Site';

// @next-codemod-ignore Cache Components adoption: this segment temporarily allows blocking.
// Remove this opt-out after verifying the segment passes validation without it.
// See: https://nextjs.org/docs/app/guides/migrating-to-cache-components


const jobs = [['Marketing Manager', '01', 'At least 6 months experience in marketing domain of Embedded Systems', 'Customer relationship management', 'Preparing product cost estimates and proposals'], ['Embedded Firmware Developer', '02', 'B.E./B.Tech in Electronics or equivalent', '6+ months experience in embedded software development', 'Microcontroller programming · C · Assembly · UART · I2C · SPI'], ['Assembler / Soldering Assembler', '02', 'Hands-on through-hole and SMD soldering', 'Knowledge of schematic, PCB layout and Gerber files', 'Team player able to work to short deadlines']];
export default function Careers() { return <Shell><main className="sub"><section className="subHero careerHero"><div className="kicker">CAREERS / IABEX</div><h1>Build electronics.<br /><em>Build your craft.</em></h1><p>Join a team where ideas become working hardware.</p></section><section className="careerWhy"><div><div className="kicker">WHY IABEX</div><h2>Work that leaves<br /><em>the screen.</em></h2></div><div className="whyGrid">{['Real Engineering', 'Growth Opportunity', 'Innovation Driven', 'Collaborative Team'].map((x, i) => <div className="reveal" key={x}><small>0{i + 1}</small><h3>{x}</h3><p>Work closely with multidisciplinary teams on products designed for real deployment.</p></div>)}</div></section><section className="openings"><div className="kicker">OPEN POSITIONS</div>{jobs.map((j, i) => <article className="job reveal" key={j[0]}><div><small>0{i + 1} / {j[1]} POSITION{j[1] === '01' ? '' : 'S'}</small><h2>{j[0]}</h2></div><ul>{j.slice(2).map(x => <li key={x}>{x}</li>)}</ul><a href={'mailto:info@iabex.in?subject=Application for ' + j[0]}>Apply now <b>↗</b></a></article>)}</section></main></Shell> }
